export const CategoriesData = [
  {
    id: "1",
    category: "motivationallove",
    slug: "love",
    label: "Love",
    subtitle: "Love short sentences to overcome sad times.",
    title: "Love ",
    navigate: "Details",
    background: require("../assets/love.png"),
  },
  {
    id: "2",
    category: "motivationalprosperity",
    slug: "prosperity",
    label: "Prosperity",
    subtitle: "Prosperity and wealth beautiful quotes.",
    title: "Prosperity ",
    navigate: "Details",
    background: require("../assets/prosperity.png"),
  },
  {
    id: "3",
    category: "motivationalsuccess",
    slug: "success",
    label: "Success",
    subtitle:
      "Reach your goals and achieve success with the help of these inspirational quotes.",
    title: "Success",
    navigate: "Details",
    background: require("../assets/success.png"),
  },
  {
    id: "4",
    category: "motivationalhealth",
    slug: "health",
    label: "Health",
    subtitle: "Get inspiration for your mind with these phrases.",
    title: "Health & Mindfulness",
    navigate: "Details",
    background: require("../assets/health.png"),
  },
  {
    id: "5",
    category: "motivationalconfidence",
    slug: "confidence",
    label: "Attitude",
    subtitle: "Keeping a Positive Attitude is very important in life.",
    title: "Positive Attitude",
    navigate: "Details",
    background: require("../assets/positive.png"),
  },
  {
    id: "6",
    category: "motivationalresilience",
    slug: "challenges",
    label: "Overcome",
    subtitle:
      "Overcome dark times, be resilient, get inspired and do not give up!",
    title: "Overcome Challenges",
    navigate: "Details",
    background: require("../assets/resilience.png"),
  },
  {
    id: "7",
    category: "motivationalpositive",
    slug: "affirmations",
    label: "Positive",
    subtitle: "Take action and stay positive.",
    title: "Positive Affirmations",
    navigate: "Details",
    background: require("../assets/affirmations.png"),
  },
  /* {
        id: 8,
        category: 'random_images',
        label: '',
        title: 'Random Images',
        navigate: 'Random Images',
        background: require('../assets/question.jpg')
    }, */
  /*   {
        id: 9,
        category: 'random_text',
        label: '',
        title: 'Random Text Quotes',
        navigate: 'Random',
        background: require('../assets/read.jpg')
    }, */
];
