export const QuotesList = [
  // Love
  {
    id: "1",
    marked: false,
    category: "motivationallove",
    picture: require("../assets/quotes/love/01.png"),
  },
  {
    id: "2",
    marked: false,
    category: "motivationallove",
    picture: require("../assets/quotes/love/02.png"),
  },
  {
    id: "3",
    marked: false,
    category: "motivationallove",
    picture: require("../assets/quotes/love/03.png"),
  },
  {
    id: "4",
    marked: false,
    category: "motivationallove",
    picture: require("../assets/quotes/love/04.png"),
  },
  {
    id: "5",
    marked: false,
    category: "motivationallove",
    picture: require("../assets/quotes/love/05.png"),
  },
  {
    id: "6",
    marked: false,
    category: "motivationallove",
    picture: require("../assets/quotes/love/06.png"),
  },
  {
    id: "7",
    marked: false,
    category: "motivationallove",
    picture: require("../assets/quotes/love/07.png"),
  },
  {
    id: "8",
    marked: false,
    category: "motivationallove",
    picture: require("../assets/quotes/love/08.png"),
  },
  {
    id: "9",
    marked: false,
    category: "motivationallove",
    picture: require("../assets/quotes/love/09.png"),
  },
  {
    id: "10",
    marked: false,
    category: "motivationallove",
    picture: require("../assets/quotes/love/10.png"),
  },
  {
    id: "11",
    marked: false,
    category: "motivationallove",
    picture: require("../assets/quotes/love/11.png"),
  },
  {
    id: "12",
    marked: false,
    category: "motivationallove",
    picture: require("../assets/quotes/love/12.png"),
  },
  // Success
  {
    id: "13",
    marked: false,
    category: "motivationalsuccess",
    picture: require("../assets/quotes/success/01.png"),
  },
  {
    id: "14",
    marked: false,
    category: "motivationalsuccess",
    picture: require("../assets/quotes/success/02.png"),
  },
  {
    id: "15",
    marked: false,
    category: "motivationalsuccess",
    picture: require("../assets/quotes/success/03.png"),
  },
  {
    id: "16",
    marked: false,
    category: "motivationalsuccess",
    picture: require("../assets/quotes/success/04.png"),
  },
  {
    id: "17",
    marked: false,
    category: "motivationalsuccess",
    picture: require("../assets/quotes/success/05.png"),
  },
  {
    id: "18",
    marked: false,
    category: "motivationalsuccess",
    picture: require("../assets/quotes/success/06.png"),
  },
  {
    id: "19",
    marked: false,
    category: "motivationalsuccess",
    picture: require("../assets/quotes/success/07.png"),
  },
  {
    id: "20",
    marked: false,
    category: "motivationalsuccess",
    picture: require("../assets/quotes/success/08.png"),
  },
  {
    id: "21",
    marked: false,
    category: "motivationalsuccess",
    picture: require("../assets/quotes/success/09.png"),
  },
  {
    id: "22",
    marked: false,
    category: "motivationalsuccess",
    picture: require("../assets/quotes/success/10.png"),
  },
  {
    id: "23",
    marked: false,
    category: "motivationalsuccess",
    picture: require("../assets/quotes/success/11.png"),
  },
  {
    id: "24",
    marked: false,
    category: "motivationalsuccess",
    picture: require("../assets/quotes/success/12.png"),
  },

  // Prosperity
  {
    id: "25",
    marked: false,
    category: "motivationalprosperity",
    picture: require("../assets/quotes/prosperity/01.png"),
  },
  {
    id: "26",
    marked: false,
    category: "motivationalprosperity",
    picture: require("../assets/quotes/prosperity/02.png"),
  },
  {
    id: "27",
    marked: false,
    category: "motivationalprosperity",
    picture: require("../assets/quotes/prosperity/03.png"),
  },
  {
    id: "28",
    marked: false,
    category: "motivationalprosperity",
    picture: require("../assets/quotes/prosperity/04.png"),
  },
  {
    id: "29",
    marked: false,
    category: "motivationalprosperity",
    picture: require("../assets/quotes/prosperity/05.png"),
  },
  {
    id: "30",
    marked: false,
    category: "motivationalprosperity",
    picture: require("../assets/quotes/prosperity/06.png"),
  },
  {
    id: "31",
    marked: false,
    category: "motivationalprosperity",
    picture: require("../assets/quotes/prosperity/07.png"),
  },
  {
    id: "32",
    marked: false,
    category: "motivationalprosperity",
    picture: require("../assets/quotes/prosperity/08.png"),
  },
  {
    id: "33",
    marked: false,
    category: "motivationalprosperity",
    picture: require("../assets/quotes/prosperity/09.png"),
  },
  {
    id: "34",
    marked: false,
    category: "motivationalprosperity",
    picture: require("../assets/quotes/prosperity/10.png"),
  },
  {
    id: "35",
    marked: false,
    category: "motivationalprosperity",
    picture: require("../assets/quotes/prosperity/11.png"),
  },
  {
    id: "36",
    marked: false,
    category: "motivationalprosperity",
    picture: require("../assets/quotes/prosperity/12.png"),
  },
  // Health
  {
    id: "37",
    marked: false,
    category: "motivationalhealth",
    picture: require("../assets/quotes/health/01.png"),
  },
  {
    id: "38",
    marked: false,
    category: "motivationalhealth",
    picture: require("../assets/quotes/health/02.png"),
  },
  {
    id: "39",
    marked: false,
    category: "motivationalhealth",
    picture: require("../assets/quotes/health/03.png"),
  },
  {
    id: "40",
    marked: false,
    category: "motivationalhealth",
    picture: require("../assets/quotes/health/04.png"),
  },
  {
    id: "41",
    marked: false,
    category: "motivationalhealth",
    picture: require("../assets/quotes/health/05.png"),
  },
  {
    id: "42",
    marked: false,
    category: "motivationalhealth",
    picture: require("../assets/quotes/health/06.png"),
  },
  {
    id: "43",
    marked: false,
    category: "motivationalhealth",
    picture: require("../assets/quotes/health/07.png"),
  },
  {
    id: "44",
    marked: false,
    category: "motivationalhealth",
    picture: require("../assets/quotes/health/08.png"),
  },
  {
    id: "45",
    marked: false,
    category: "motivationalhealth",
    picture: require("../assets/quotes/health/09.png"),
  },
  {
    id: "46",
    marked: false,
    category: "motivationalhealth",
    picture: require("../assets/quotes/health/10.png"),
  },
  {
    id: "47",
    marked: false,
    category: "motivationalhealth",
    picture: require("../assets/quotes/health/11.png"),
  },
  {
    id: "48",
    marked: false,
    category: "motivationalhealth",
    picture: require("../assets/quotes/health/12.png"),
  },

  // positive
  {
    id: "49",
    marked: false,
    category: "motivationalconfidence",
    picture: require("../assets/quotes/positiveattitude/01.png"),
  },
  {
    id: "50",
    marked: false,
    category: "motivationalconfidence",
    picture: require("../assets/quotes/positiveattitude/02.png"),
  },
  {
    id: "51",
    marked: false,
    category: "motivationalconfidence",
    picture: require("../assets/quotes/positiveattitude/03.png"),
  },
  {
    id: "52",
    marked: false,
    category: "motivationalconfidence",
    picture: require("../assets/quotes/positiveattitude/04.png"),
  },
  {
    id: "53",
    marked: false,
    category: "motivationalconfidence",
    picture: require("../assets/quotes/positiveattitude/05.png"),
  },
  {
    id: "54",
    marked: false,
    category: "motivationalconfidence",
    picture: require("../assets/quotes/positiveattitude/06.png"),
  },
  {
    id: "55",
    marked: false,
    category: "motivationalconfidence",
    picture: require("../assets/quotes/positiveattitude/07.png"),
  },
  {
    id: "56",
    marked: false,
    category: "motivationalconfidence",
    picture: require("../assets/quotes/positiveattitude/08.png"),
  },
  {
    id: "57",
    marked: false,
    category: "motivationalconfidence",
    picture: require("../assets/quotes/positiveattitude/09.png"),
  },
  {
    id: "58",
    marked: false,
    category: "motivationalconfidence",
    picture: require("../assets/quotes/positiveattitude/10.png"),
  },
  {
    id: "59",
    marked: false,
    category: "motivationalconfidence",
    picture: require("../assets/quotes/positiveattitude/11.png"),
  },
  {
    id: "60",
    marked: false,
    category: "motivationalconfidence",
    picture: require("../assets/quotes/positiveattitude/12.png"),
  },
  // resilience
  {
    id: "61",
    marked: false,
    category: "motivationalresilience",
    picture: require("../assets/quotes/resilience/01.png"),
  },
  {
    id: "62",
    marked: false,
    category: "motivationalresilience",
    picture: require("../assets/quotes/resilience/02.png"),
  },
  {
    id: "63",
    marked: false,
    category: "motivationalresilience",
    picture: require("../assets/quotes/resilience/03.png"),
  },
  {
    id: "64",
    marked: false,
    category: "motivationalresilience",
    picture: require("../assets/quotes/resilience/04.png"),
  },
  {
    id: "65",
    marked: false,
    category: "motivationalresilience",
    picture: require("../assets/quotes/resilience/05.png"),
  },
  {
    id: "66",
    marked: false,
    category: "motivationalresilience",
    picture: require("../assets/quotes/resilience/06.png"),
  },
  {
    id: "67",
    marked: false,
    category: "motivationalresilience",
    picture: require("../assets/quotes/resilience/07.png"),
  },
  {
    id: "68",
    marked: false,
    category: "motivationalresilience",
    picture: require("../assets/quotes/resilience/08.png"),
  },
  {
    id: "69",
    marked: false,
    category: "motivationalresilience",
    picture: require("../assets/quotes/resilience/09.png"),
  },
  {
    id: "70",
    marked: false,
    category: "motivationalresilience",
    picture: require("../assets/quotes/resilience/10.png"),
  },
  {
    id: "71",
    marked: false,
    category: "motivationalresilience",
    picture: require("../assets/quotes/resilience/11.png"),
  },
  {
    id: "72",
    marked: false,
    category: "motivationalresilience",
    picture: require("../assets/quotes/resilience/12.png"),
  },
  // affirmations
  {
    id: "73",
    marked: false,
    category: "motivationalpositive",
    picture: require("../assets/quotes/affirmations/01.png"),
  },
  {
    id: "74",
    marked: false,
    category: "motivationalpositive",
    picture: require("../assets/quotes/affirmations/02.png"),
  },
  {
    id: "75",
    marked: false,
    category: "motivationalpositive",
    picture: require("../assets/quotes/affirmations/03.png"),
  },
  {
    id: "76",
    marked: false,
    category: "motivationalpositive",
    picture: require("../assets/quotes/affirmations/04.png"),
  },
  {
    id: "77",
    marked: false,
    category: "motivationalpositive",
    picture: require("../assets/quotes/affirmations/05.png"),
  },
  {
    id: "78",
    marked: false,
    category: "motivationalpositive",
    picture: require("../assets/quotes/affirmations/06.png"),
  },
  {
    id: "79",
    marked: false,
    category: "motivationalpositive",
    picture: require("../assets/quotes/affirmations/07.png"),
  },
  {
    id: "80",
    marked: false,
    category: "motivationalpositive",
    picture: require("../assets/quotes/affirmations/08.png"),
  },
  {
    id: "81",
    marked: false,
    category: "motivationalpositive",
    picture: require("../assets/quotes/affirmations/09.png"),
  },
  {
    id: "82",
    marked: false,
    category: "motivationalpositive",
    picture: require("../assets/quotes/affirmations/10.png"),
  },
  {
    id: "83",
    marked: false,
    category: "motivationalpositive",
    picture: require("../assets/quotes/affirmations/11.png"),
  },
  {
    id: "84",
    marked: false,
    category: "motivationalpositive",
    picture: require("../assets/quotes/affirmations/12.png"),
  },
];
